=== phatd0nut/wt3labbar/L2/xml/courselist.dtd
<!--
courselist
	subject
	course*
		code
		title
		credits
		description?
		contact?
			name
			email
		moreinfo
			attr: url
-->

<!ELEMENT courselist (subject, course*)>
	<!ELEMENT subject (#PCDATA)>
	<!ELEMENT course (code, title, credits, description?, contact?, moreinfo)>
		<!ELEMENT code (#PCDATA)>
		<!ELEMENT title (#PCDATA)>
		<!ELEMENT credits (#PCDATA)>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT contact (name, email)>
			<!ELEMENT name (#PCDATA)>
			<!ELEMENT email (#PCDATA)>
		<!ELEMENT moreinfo EMPTY>
				<!ATTLIST moreinfo url CDATA #REQUIRED>

=== phatd0nut/wt3labbar/L2/xml/courselist3.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE courselist SYSTEM "courselist.dtd">

<courselist>
	
	<subject>Svenska</subject>
	
	<course>
		<code>1SV108</code>
		<title>Akademiskt skrivande</title>
		<credits>7,5</credits>
		<description>I kursen utvecklar de studerande kunskap om och färdigheter i det vetenskapliga skrivandet.</description>
		<contact>
			<name>Claes Ohlsson</name>
			<email>claes.ohlsson@lnu.se</email>
		</contact>
		<moreinfo url="http://lnu.se/utbildning/kurser/1SV108"/>
	</course>
	
	<course>
		<code>1SV109</code>
		<title>Vikingarnas språk</title>
		<credits>7,5</credits>
		<description>Språket i det vikingatida Sverige utifrån bevarat källmaterial och med utblick mot hela Skandinavien.</description>
		<contact>
			<name>Claes Ohlsson</name>
			<email>claes.ohlsson@lnu.se</email>
		</contact>
		<moreinfo url="http://lnu.se/utbildning/kurser/1SV109"/>
	</course>
	
	<course>
		<code>1SV208</code>
		<title>Grammatik för lärare</title>
		<credits>7,5</credits>
		<description>Grammatik och grammatikdidaktik med fokus på att väcka förståelse och intresse för språkets struktur.</description>
		<moreinfo url="http://lnu.se/utbildning/kurser/1SV208"/>
	</course>
	
</courselist>

=== phatd0nut/wt3labbar/L2/xml/courselist2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE courselist SYSTEM "courselist.dtd">

<courselist>
	
	<subject>Musikvetenskap</subject>
	
	<course>
		<code>1MV111</code>
		<title>Musik i film och TV</title>
		<credits>7,5</credits>
		<description>Filmmusik ur ett historiskt perspektiv, från stumfilmen till musiken i dagens film.</description>
		<moreinfo url="http://lnu.se/utbildning/kurser/1MV111"/>
	</course>
	
	<course>
		<code>1MV338</code>
		<title>Musikteori I</title>
		<credits>7,5</credits>
		<description>Musikens kod: tidsperspektiv, musiklyssning, tonförråd, ackordbygge och funktioner.</description>
		<contact>
			<name>Hans-Erik Holgersson</name>
			<email>hans-erik.holgersson@lnu.se</email>
		</contact>
		<moreinfo url="http://lnu.se/utbildning/kurser/1MV338"/>
	</course>
	
	<course>
		<code>1MV103</code>
		<title>Musikmiljöer i Europa genom tiderna</title>
		<credits>15</credits>
		<contact>
			<name>Karin Larsson Eriksson</name>
			<email>karin.eriksson@lnu.se</email>
		</contact>
		<moreinfo url="http://lnu.se/utbildning/kurser/1MV103"/>
	</course>
	
</courselist>

=== phatd0nut/wt3labbar/L2/xml/courselist1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE courselist SYSTEM "courselist.dtd">

<courselist>
	
	<subject>Medieteknik</subject>
	
	<course>
		<code>1ME311</code>
		<title>Digitala medier</title>
		<credits>7,5</credits>
		<description>Grafik, ljud, text och layout i en multimedial kontext.</description>
		<contact>
			<name>Romain Herault</name>
			<email>romain.herault@lnu.se</email>
		</contact>
		<moreinfo url="http://lnu.se/utbildning/kurser/1ME311"/>
	</course>
	
	<course>
		<code>1ME314</code>
		<title>Videoproduktion 1</title>
		<credits>7,5</credits>
		<description>Olika delar i videoproduktion, såsom planering, filmning, redigering och distribution.</description>
		<moreinfo url="http://lnu.se/utbildning/kurser/1ME314"/>
	</course>
	
	<course>
		<code>1ME323</code>
		<title>Webbteknik 3</title>
		<credits>7,5</credits>
		<description>Struktur och objekt i data och programkod, sökmotoroptimering, m.m.</description>
		<contact>
			<name>Rune Körnefors</name>
			<email>rune.kornefors@lnu.se</email>
		</contact>
		<moreinfo url="http://lnu.se/utbildning/kurser/1ME323"/>
	</course>
	
	<course>
		<code>1ME324</code>
		<title>Webbteknik 4</title>
		<credits>7,5</credits>
		<description>Serverbaserad webbutveckling med skriptspråket PHP och databashantering med MySQL.</description>
		<contact>
			<name>Henrik Andersen</name>
			<email>henrik.andersen@lnu.se</email>
		</contact>
		<moreinfo url="http://lnu.se/utbildning/kurser/1ME324"/>
	</course>
	
	<course>
		<code>1ME331</code>
		<title>Interaktionsdesign 1</title>
		<credits>7,5</credits>
		<description>Grunderna i användbarhet och interaktion med fokus på användaren.</description>
		<moreinfo url="http://lnu.se/utbildning/kurser/1ME331"/>
	</course>
	
</courselist>
