=== phatd0nut/wt3labbar/L1/filmerochserier.dtd
<!-- filmerOchSerier
    recension+
        titel
            attr: typ (film|serie)
        genre
        imdb
        beskrivning
        bild
            attr: bild-url
        streaming?
            attr: streamingtjänst? (netflix|hbo)
            länk?
-->

<!ELEMENT filmerOchSerier (recension+)>
    <!ELEMENT recension (titel, genre, imdb, beskrivning, bild, streaming?)>
    <!ELEMENT titel (#PCDATA)>
        <!ATTLIST titel typ (film|serie) #REQUIRED>
    <!ELEMENT genre (#PCDATA)>
    <!ELEMENT imdb (#PCDATA)>
    <!ELEMENT beskrivning (#PCDATA)>
    <!ELEMENT bild EMPTY>
        <!ATTLIST bild bild-url CDATA #REQUIRED>
    <!ELEMENT streaming (link?)>
       <!ATTLIST streaming streamingservice (netflix|hbo) #IMPLIED>
       <!ELEMENT link (#PCDATA)>

=== phatd0nut/wt3labbar/L1/BreakingBad.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE filmerOchSerier SYSTEM "filmerochserier.dtd">

<filmerOchSerier>

    <recension>
        <titel typ="serie">Breaking Bad</titel>
        <genre>Brott, Drama, Thriller</genre>
        <imdb>9.5</imdb>
        <beskrivning>En kemilärare med diagnosen inoperabel lungcancer vänder sig till att tillverka och sälja metamfetamin tillsammans med en före detta elev för att säkra sin familjs framtid.</beskrivning>
        <bild bild-url="https://m.media-amazon.com/images/M/MV5BYTU3NWI5OGMtZmZhNy00MjVmLTk1YzAtZjA3ZDA3NzcyNDUxXkEyXkFqcGdeQXVyODY5Njk4Njc@._V1_.jpg"/>
        <streaming streamingservice="netflix">
            <link>https://www.netflix.com/se/title/70143836</link>
        </streaming>
    </recension>

</filmerOchSerier>

=== phatd0nut/wt3labbar/L1/GameOfThrones.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE filmerOchSerier SYSTEM "filmerochserier.dtd">

<filmerOchSerier>

    <recension>
        <titel typ="serie">Game of Thrones</titel>
        <genre>Action, Äventyr, Drama</genre>
        <imdb>9.2</imdb>
        <beskrivning>
            Nio adelsfamiljer slåss om kontroll över Westeros länder, medan en uråldrig fiende återvänder efter att ha varit vilande i årtusenden.</beskrivning>
        <bild bild-url="https://i1.sndcdn.com/artworks-W8KXhQeXZrv2YSJO-ctOyHA-t500x500.jpg"/>
        <streaming streamingservice="hbo">
            <link>https://www.hbomax.com/se/sv/series/urn:hbo:series:GVU2cggagzYNJjhsJATwolinknk></link>
        </streaming>
    </recension>

</filmerOchSerier>

=== phatd0nut/wt3labbar/L1/Avatar2.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE filmerOchSerier SYSTEM "filmerochserier.dtd">

<filmerOchSerier>

    <recension>
        <titel typ="film">Avatar: The Way of Water</titel>
        <genre>Action, Äventyr, Fantasy</genre>
        <imdb>7.9</imdb>
        <beskrivning>Jake Sully bor med sin nyfunna familj som bildats på den extrasolära månen Pandora. När ett välbekant hot återvänder för att avsluta det som tidigare påbörjades måste Jake samarbeta med Neytiri och Na'vi-rasens armé för att skydda deras hem.</beskrivning>
        <bild bild-url="https://m.media-amazon.com/images/M/MV5BYjhiNjBlODctY2ZiOC00YjVlLWFlNzAtNTVhNzM1YjI1NzMxXkEyXkFqcGdeQXVyMjQxNTE1MDA@._V1_FMjpg_UX1000_.jpg"/>
        <streaming/>
    </recension>

</filmerOchSerier>
